language: node_js
node_js:
- '4'
- '5'
sudo: false
before_script:
notifications:
  email: true
after_failure: cat /home/travis/build/rogerpadilla/angular2-minimalist-starter/npm-debug.log
branches:
  only:
  - master
